version: 2.1
jobs:
  build:
    docker:
      - image: circleci/openjdk:11
    steps:
      - checkout
      - run: echo "Hello, docker!"
  deploy:
    docker:
      - image: docker:20.10.9
    steps:
      - checkout
      - run:
          name: Build Docker image
          command: |
            docker build -t my-image .
      - run:
          name: Push Docker image to registry
          command: |
            echo $DOCKERHUB_PASSWORD | docker login --username $DOCKERHUB_USERNAME --password-stdin
            docker tag my-image $DOCKERHUB_USERNAME/my-image:latest
            docker push $DOCKERHUB_USERNAME/my-image:latest
workflows:
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
