version: 2.1
jobs:
  build:
    working_directory: /tmp/build
    docker:
      - image: circleci/openjdk:11-stretch
    steps:
      - checkout
      - run: echo "Hello, docker!"
  deploy:
    working_directory: /tmp/build
    docker:
      - image: docker:20.10.9
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build Docker image
          command: |
            docker build -t my-image .
      - run:
          name: SonarCloud Analysis
          command: |
            sonar-scanner \
              -Dsonar.projectKey=1234 \
              -Dsonar.organization=12 \
              -Dsonar.host.url=https://sonarcloud.io \
              -Dsonar.login=232 \
              -Dsonar.sources=./src \
              -Dsonar.java.binaries=./target/classes
workflows:
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master